### ISSUE TITLE
[Question] Management of synchronisation between state and brower cookie

### ISSUE THREAD

**Issue by be-next-hotdog** [devCrossNet/vue-starter#145]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] or maybe just a painful question
```

## Versions.
```
browser: Chrome
browser version: ver. 66
operating system: Mac OS 10.13
```

Hi, folks, @devCrossNet, this might go for digging out a solution face to this typical problematic under SSR.
I currently store a `userLastSelectedLocale` in browser cookie and wish to initialize the `locale` state connected to this `userLastSelectedLocale` value if it exist in cookie. But obviously it could not possibly be feasible cuz we are not able to access to browser cookie (or document.cookie) until browser side arrives at `mounted` cycle, and up to this moment, all initialisation of state and computed values should have done during server side rendering and before the `created` hook.

So what would be the best solution to fix this or have to solve it in storing only cookie in server session ? 

Any tips or suggestions highly appreciated !

**Comment by devCrossNet** [comment]
@be-next-hotdog hey I am not really sure if I understand your use-case correctly.

How does it differ from the one I already included? (https://github.com/devCrossNet/vue-starter/blob/master/src/server/isomorphic.ts#L51)

I think you have to gove me a little bit more context to help you 😊

**Comment by be-next-hotdog** [comment]
Supposing that we stored `{ userSelectedLocale: 'en_US' }` in browser side cookie. 

some quick dumb codes:
```
// in i18n config
let userSelectedLocale

if (process.browser) {
  userSelectedLocale = VueCookie.get('userSelectedLocale')
}

let defaultLocale = userSelectedLocale || 'en_GB'

... ...

const i18n = new VueI18n({
  locale: defaultLocale
})

export default i18n
```
And :
```
// in my locale state module 
import i18n from '...'

export const state = {
  currentLocale: i18n.locale
}
```

We agreed that the `locale` value remains always `"en_US"` even after on browser side components mounted,  also all the `computed values` attached to this locale state by a Getter remain `"en_US"`, cuz initialisation of state has done yet on server side without finding any meaningful value (VueCookie.get('userSelectedLocale') = null normally).

**Comment by devCrossNet** [comment]
this whole use case is already included in the vue-starter. it uses a persist middleware to save the app module in a cookie. and it gets extracted and merged on the server-side before rendering in `isomorphic. ts`.

it is also optimized to not have any default locales in the app bundle generated by webpack.

I recommend you to read the docs: 

https://vue-starter.herokuapp.com/docs/guide/i18n.html
and
https://vue-starter.herokuapp.com/docs/docs/i18n.html

if this is not what you're looking for, please let me know 👍

**Comment by devCrossNet** [comment]
I am very sorry, I struggle to answer this. Maybe it's something lost in translation.

Let me reflect. you want to save the `en_GB` locale in a cookie and set it as the default locale in the i18n plugin, but just on the client side?

you could read the cookie value and put it directly in the default state, or just initialize the i18n plugin with the cookie value.

to be honest, I prefer the solution in the vue-starter because that way the app is already rendered with the right language.

If this still doesn't help you, we should have a hang out where you share your screen or something like that.

**Comment by be-next-hotdog** [comment]
You just misunderstood guy, what you did matches perfectly the usual requirements for how to handle the locale state / async loading et etc. 
I consider the locale selections in 2 user case : 
1. locale setting saved in user profile data (persisted in db i.e.), would be in charge for the 1st visit of your app ;
2. locale selected during navigation (for example most of people prefer spending times on browsing app store or some marketplaces of other regions without changing the locale setting in their profile, because probably they could make a purchase more easily on their local store) and in this case, on our app, it 'd better run a `browser locale setting over user profile locale setting` check process to fetch '/products?region=my_last_selected_locale_saved_in_browser_cookie'.

Thus, what I expected was trying to replace the state locale value by a cookie item value in src/client/index.ts ?

**Comment by devCrossNet** [comment]
Hey, @be-next-hotdog.

> locale setting saved in user profile data (persisted in db i.e.), would be in charge for the 1st visit of your app ;

This use-case is not supported by default in the vue-starter.

> Thus, what I expected was trying to replace the state locale value by a cookie item value in src/client/index.ts ?

This is exactly what I implemented.
There is an `app` state which has a locale attribute. this state can be overwritten by a user interaction.
The user choice is saved to a cookie, hydrated on the server and put back to the client.

please have a look at the following lines:
- state which can be changed by the user: https://github.com/devCrossNet/vue-starter/blob/master/src/app/app/state.ts#L4
- save to cookie: https://github.com/devCrossNet/vue-starter/blob/master/src/app/store.ts#L39
- read cookie and locale on the server: https://github.com/devCrossNet/vue-starter/blob/master/src/server/isomorphic.ts#L35
- set locale that was saved in the cookie in the client: https://github.com/devCrossNet/vue-starter/blob/master/src/client/index.ts#L21

Anyway if you want to implement your own logic, these are the files you should change in order to get your use-case implemented.

But keep in mind that the right default messages should be passed to the client as you see in this line: https://github.com/devCrossNet/vue-starter/blob/master/src/server/isomorphic.ts#L56

But this whole logic is new in version 1 of the vue-starter, if you're using an older version, I recommend to update your code to version 1. I added a lot of improvements (and docs based on this version).

**Comment by be-next-hotdog** [comment]
Sorry to reply so late, guys.

Actually, I captured just the necessary SSR scripts from this project instead of cloning all, in considering of managing a minimum viable stack, besides, my friends are not ready to programme with TS. I'll try to implement this feature (state persistence and merge) what you enhanced recently.

Furthermore, speaking of our whole need, this synchronous locale state involved also a segment of route : 
`/[:locale]/page/section/details`

and I had to add the default route in a remedial way before the rendering on both sides (sev entry and browser entry scripts) : 

```javascript
  router.addRoutes([{
      path: '/',
      name: 'default',
      redirect: {
          name: 'home',
          params: { currentLocale: Cookies.get('userSelectedLocale') || XXXX } // XXXX: i18n.locale or locale state
      }
  }])
```

Otherwise the default (dynamic lang/locale) route picks up always the default locale `en_GB`. Or once again I implemented it in a way ?

**Comment by devCrossNet** [comment]
hey @be-next-hotdog,

that is a use-case I don't have implemented yet and I have no quick solution to it.

It's really difficult for me to support someone who has just copied a small piece of the vue-starter code. I hope you can understand that I close this issue because it is not related to this project.

You can create a feature request and describe in detail what the vue-starter should support.

**Comment by be-next-hotdog** [comment]
@devCrossNet no prob, you're right 👍
