### ISSUE TITLE
counter does not work on iPhone

### ISSUE THREAD

**Issue by tvogt** [devCrossNet/vue-starter#170]
## Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

## Versions.
```
browser: Mobile Safari
browser version: unknown
operating system: iOS 11.3.1
```

## Repro steps.

clone, install, run
access system on local network (computername:3000) from iPhone
site comes up, everything fine
go to counter page
press increment and decrement buttons
number does not change

**Comment by devCrossNet** [comment]
hey @tvogt,

did you already figure out why it's not working? If it's critical for you that it works right now, I recommend using [ngrok](https://ngrok.com/).

That's much better for your use case 👍

**Comment by devCrossNet** [comment]
@tvogt forget about the ngrok thing. the problem is that you have a different URL than the baseUrl in the file `./src/app/config/default.json`. That leads to a CORS violation.

you have two options:
- implement CORS in the express app (guess I wouldn't do this)
- change the base URL (much easier)

I hope that helps :-)

**Comment by tvogt** [comment]
yeah, it's not important. Just thought the demo app should have simple things working, or people implementing more complicated logic based on it will hit that wall and wonder why.

**Comment by devCrossNet** [comment]
@tvogt I thought about it yesterday and I think we can discuss a better solution. I work always with microservices, that means I don't use the express app as an API.

The issue is that we need a hardcoded URL for the XHR requests because relative paths don't work on the server-side.

If you have an idea how it should work by default, let me know. But I guess this issue is tightly coupled to your overall architecture in the project.

**Comment by devCrossNet** [comment]
I would be happy if you can create a PR for that. I thought that CORS is something every web-developer knows about. I will rethink the use-case I want to cover with the `HttpService` and try to come up with a generic solution _**or**_ documentation

**Comment by devCrossNet** [comment]
I added a new section to the docs where I describe how to set up the architecture for the vue-starter, anything else will not be covered by our support. https://vue-starter.herokuapp.com/docs/introduction.html#recommended-architecture
